# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32a916faab8df660aa01ac5d966e5badf16687507fc550fb61e1872cfa902839c07de7ce03155c07a621db1687fde986ca1a6af83e3662341c7f571086fa4240

test:
  secret_key_base: 37debebe9966452a300a432a9c4f106b61e939e3688089ab68566d53de35e4ee5dc41fdd8479760e4ae9cea19024db51bba60fe2640df61b952a4d63ff24b705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
